### ISSUE TITLE
[BUG] OST: invalid table type

### ISSUE THREAD

**Issue by eviltik** [mooijtech/go-pst#27]
**Describe the bug**
After change the file path to an OST file in the example, then go build / run , i got "invalid table type" error.

**To Reproduce**
```
I've used the same code provided in your example and but on an OST file.
```

**Expected behavior**
Should run without error

**Stack trace**
```
Initializing...
panic: Failed to open PST file: go-pst: invalid table type
github.com/mooijtech/go-pst/v5/pkg.(*File).GetPropertyContext
	/home/eviltik/go/pkg/mod/github.com/mooijtech/go-pst/v5@v5.0.0/pkg/property_context.go:66
github.com/mooijtech/go-pst/v5/pkg.(*File).GetNameToIDMap
	/home/eviltik/go/pkg/mod/github.com/mooijtech/go-pst/v5@v5.0.0/pkg/name_to_id_map.go:111
github.com/mooijtech/go-pst/v5/pkg.NewFromReaderWithBTrees
	/home/eviltik/go/pkg/mod/github.com/mooijtech/go-pst/v5@v5.0.0/pkg/file.go:132
github.com/mooijtech/go-pst/v5/pkg.NewFromReader
	/home/eviltik/go/pkg/mod/github.com/mooijtech/go-pst/v5@v5.0.0/pkg/file.go:52
github.com/mooijtech/go-pst/v5/pkg.NewFromFile
	/home/eviltik/go/pkg/mod/github.com/mooijtech/go-pst/v5@v5.0.0/pkg/file.go:47
main.main
	/home/eviltik/toto/main.go:18
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594
github.com/mooijtech/go-pst/v5/pkg.(*File).GetNameToIDMap
	/home/eviltik/go/pkg/mod/github.com/mooijtech/go-pst/v5@v5.0.0/pkg/name_to_id_map.go:114
github.com/mooijtech/go-pst/v5/pkg.NewFromReaderWithBTrees
	/home/eviltik/go/pkg/mod/github.com/mooijtech/go-pst/v5@v5.0.0/pkg/file.go:132
github.com/mooijtech/go-pst/v5/pkg.NewFromReader
	/home/eviltik/go/pkg/mod/github.com/mooijtech/go-pst/v5@v5.0.0/pkg/file.go:52
github.com/mooijtech/go-pst/v5/pkg.NewFromFile
	/home/eviltik/go/pkg/mod/github.com/mooijtech/go-pst/v5@v5.0.0/pkg/file.go:47
main.main
	/home/eviltik/toto/main.go:18
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594
github.com/mooijtech/go-pst/v5/pkg.NewFromReaderWithBTrees
	/home/eviltik/go/pkg/mod/github.com/mooijtech/go-pst/v5@v5.0.0/pkg/file.go:135
github.com/mooijtech/go-pst/v5/pkg.NewFromReader
	/home/eviltik/go/pkg/mod/github.com/mooijtech/go-pst/v5@v5.0.0/pkg/file.go:52
github.com/mooijtech/go-pst/v5/pkg.NewFromFile
	/home/eviltik/go/pkg/mod/github.com/mooijtech/go-pst/v5@v5.0.0/pkg/file.go:47
main.main
	/home/eviltik/toto/main.go:18
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594


goroutine 1 [running]:
main.main()
	/home/eviltik/toto/main.go:21 +0x239
```

**Platform (please complete the following information):**
- go-pst v5
- go version go1.19.2 linux/amd64

**Comment by mooijtech** [comment]
@eviltik Thank you for your report! 
There are minor differences between PST and OST files (mainly byte sizes).
I currently do not have an OST file to test go-pst with (I have tested on PST files), but I would like to add support.
I will look at the required modifications to support OST.
